import type { CollaborativeWorkspaceService, PlanChangeInput } from '../../application/src/index.ts';
import { compileChangePlanToScenarioPatch } from '../../model/src/index.ts';
import { runScenarioCapacityAnalysis } from '../../evidence/src/index.ts';

export type ToolActivityStatus = 'success' | 'error' | 'cancelled';
export interface ToolActivityEvent { id:string; tool:string; readOnly:boolean; status:ToolActivityStatus; startedAt:string; durationMs:number; summary:string; actor:'agent'; }
export interface ToolExecuteOptions { signal?:AbortSignal }
export interface WebMCPTool { name:string; title?:string; description:string; inputSchema?:Record<string,unknown>; annotations?:{readOnlyHint?:boolean;untrustedContentHint?:boolean}; execute:(input:Record<string,unknown>,options?:ToolExecuteOptions)=>unknown|Promise<unknown> }
export interface DiscoveredWebMCPTool { name:string; title?:string; description:string; inputSchema?:string|Record<string,unknown>; annotations?:{readOnlyHint?:boolean;untrustedContentHint?:boolean}; origin?:string }
export interface ModelContextLike {
  registerTool(tool:WebMCPTool, options?:{signal?:AbortSignal}):Promise<void>|void;
  getTools?(options?:{fromOrigins?:string[]}):Promise<DiscoveredWebMCPTool[]>;
  executeTool?(tool:DiscoveredWebMCPTool,input:string,options?:{signal?:AbortSignal}):Promise<unknown>;
  addEventListener?(type:'toolchange',listener:(event:Event)=>void):void;
  removeEventListener?(type:'toolchange',listener:(event:Event)=>void):void;
}
export interface WebMCPRegistrationOptions { onActivity?(event:ToolActivityEvent):void; onToolSetChanged?(names:string[]):void }
export interface WebMCPRegistration { refresh():Promise<string[]>; dispose():void; getRegisteredNames():string[] }

export const CORE_TOOL_NAMES = ['inspect_workspace','inspect_selection','inspect_plan','inspect_analysis','simulate_change','add_plan_change','remove_plan_change','set_plan_constraints','set_plan_restriction','analyze_plan','run_contingencies','verify_plan'] as const;
export const VIOLATION_TOOL_NAMES = ['inspect_violation','focus_violation','find_bottlenecks'] as const;
export const MITIGATION_TOOL_NAMES = ['propose_mitigation'] as const;
export const DESIGN_TOOL_NAMES = ['compare_mitigation_variants'] as const;
export const PROPOSAL_TOOL_NAMES = ['accept_proposal_change','reject_proposal_change','discard_proposal'] as const;
export const ALL_PRODUCT_TOOL_NAMES = [...CORE_TOOL_NAMES,...VIOLATION_TOOL_NAMES,...MITIGATION_TOOL_NAMES,...DESIGN_TOOL_NAMES,...PROPOSAL_TOOL_NAMES] as const;

function schema(properties:Record<string,unknown>={},required:string[]=[]):Record<string,unknown>{return {type:'object',properties,...(required.length?{required}:{}),additionalProperties:false};}
function elapsed(start:number){return Math.round((Date.now()-start)*1000)/1000;}
function abortLike(error:unknown){return error instanceof Error && error.name==='AbortError';}
function asString(v:unknown,label:string){if(typeof v!=='string'||!v.trim())throw new Error(`${label} must be a non-empty string.`);return v.trim();}
function asOptionalString(v:unknown,label:string){return v===undefined?undefined:asString(v,label);}
function asNumber(v:unknown,label:string){if(typeof v!=='number'||!Number.isFinite(v))throw new Error(`${label} must be a finite number.`);return v;}
function asBoolean(v:unknown,label:string){if(typeof v!=='boolean')throw new Error(`${label} must be a boolean.`);return v;}
function asStringArray(v:unknown,label:string){if(!Array.isArray(v))throw new Error(`${label} must be an array of strings.`);return v.map((item,index)=>asString(item,`${label}[${index}]`));}
function asSelectionTarget(v:unknown){if(v===undefined)return undefined;if(v!=='selection')throw new Error('target must be "selection" when provided.');return 'selection' as const;}
function inRange(value:number,label:string,min:number,max?:number){if(value<min||(max!==undefined&&value>max))throw new Error(`${label} must be ${max===undefined?`>= ${min}`:`between ${min} and ${max}`}.`);return value;}
function summarize(result:unknown):string { if(result===null)return 'no result'; if(typeof result==='string')return result.slice(0,160); if(typeof result==='object'&&result){const r=result as Record<string,unknown>; if(typeof r.status==='string')return r.status; if(typeof r.state==='string')return r.state; if(typeof r.verdict==='string')return r.verdict; if('proposalCount'in r)return `${String(r.proposalCount)} proposal change(s)`;} return 'completed'; }

function wrap(service:CollaborativeWorkspaceService,name:string,readOnly:boolean,options:WebMCPRegistrationOptions,fn:(input:Record<string,unknown>,exec?:ToolExecuteOptions)=>unknown|Promise<unknown>,after?:()=>Promise<void>):WebMCPTool['execute']{
  return async(input,exec)=>{const start=Date.now(),startedAt=new Date(start).toISOString();try{if(exec?.signal?.aborted){const e=new Error('Tool execution cancelled');e.name='AbortError';throw e;}const result=await fn(input,exec);if(exec?.signal?.aborted){const e=new Error('Tool execution cancelled');e.name='AbortError';throw e;}options.onActivity?.({id:`${name}:${start}`,tool:name,readOnly,status:'success',startedAt,durationMs:elapsed(start),summary:summarize(result),actor:'agent'});await after?.();return result;}catch(error){const cancelled=exec?.signal?.aborted||abortLike(error);options.onActivity?.({id:`${name}:${start}`,tool:name,readOnly,status:cancelled?'cancelled':'error',startedAt,durationMs:elapsed(start),summary:cancelled?'cancelled':error instanceof Error?error.message:'tool failed',actor:'agent'});await after?.();throw error;}};
}

function buildTools(service:CollaborativeWorkspaceService,options:WebMCPRegistrationOptions,refresh:()=>Promise<void>):Map<string,WebMCPTool>{
  const tools=new Map<string,WebMCPTool>();
  const add=(tool:Omit<WebMCPTool,'execute'>&{execute:(input:Record<string,unknown>,options?:ToolExecuteOptions)=>unknown|Promise<unknown>})=>tools.set(tool.name,tool);
  const ro={readOnlyHint:true,untrustedContentHint:true}, mut={readOnlyHint:false,untrustedContentHint:true};
  add({name:'inspect_workspace',title:'Inspect shared InfraTwin workspace',description:'Read a compact summary of the live browser-local Network + ChangePlan, including current human selection, constraints, locks, analysis freshness, proposal state, and verification. Read-only.',inputSchema:schema(),annotations:ro,execute:wrap(service,'inspect_workspace',true,options,()=>service.getWorkspaceSummary())});
  add({name:'inspect_selection',title:'Inspect human selection',description:'Read the semantic node, link, or demand the human currently selected in the live topology. Returns an explicit no-selection state and never changes engineering state.',inputSchema:schema(),annotations:ro,execute:wrap(service,'inspect_selection',true,options,()=>service.inspectSelection())});
  add({name:'inspect_plan',title:'Inspect visible ChangePlan',description:'Read the current visible ChangePlan, human/agent-authored changes, constraints, locks, proposal decisions, and stale proposal state. Read-only.',inputSchema:schema(),annotations:ro,execute:wrap(service,'inspect_plan',true,options,()=>service.inspectPlan())});
  add({name:'inspect_analysis',title:'Inspect deterministic plan analysis',description:'Read the latest published deterministic analysis for the current ChangePlan and whether it is current or stale. Read-only.',inputSchema:schema(),annotations:ro,execute:wrap(service,'inspect_analysis',true,options,()=>service.inspectAnalysis())});
  add({name:'simulate_change',title:'Simulate a read-only what-if',description:'Run a read-only hypothetical link outage or demand growth against the current live plan without modifying the visible ChangePlan. Use add_plan_change when the user requests a persistent shared edit.',inputSchema:schema({type:{type:'string',enum:['disable_link','demand_growth']},linkId:{type:'string'},target:{type:'string',enum:['selection']},demandIds:{type:'array',items:{type:'string'}},multiplier:{type:'number',minimum:0}},['type']),annotations:ro,execute:wrap(service,'simulate_change',true,options,(input)=>{const project=service.getProject(),base=compileChangePlanToScenarioPatch(project,service.getChangePlan());const patch=JSON.parse(JSON.stringify(base));patch.id='webmcp-hypothetical';patch.name='Agent read-only hypothetical';const type=asString(input.type,'type'),target=asSelectionTarget(input.target);if(type==='disable_link'){let id=target==='selection'?'':asString(input.linkId,'linkId');if(target==='selection'){const s=service.getSelection();if(!s||s.kind!=='link')throw new Error('Current selection must be a link.');id=s.id;}if(!project.links.some(l=>l.id===id))throw new Error(`Unknown link ${id}`);patch.disabledLinkIds=[...new Set([...patch.disabledLinkIds,id])].sort();}else if(type==='demand_growth'){let ids:string[];if(target==='selection'){const selection=service.getSelection();if(!selection||selection.kind!=='demand')throw new Error('Current selection must be a demand.');ids=[selection.id];}else ids=asStringArray(input.demandIds,'demandIds');if(!ids.length)throw new Error('At least one demand id or a current demand selection is required.');const multiplier=inRange(asNumber(input.multiplier,'multiplier'),'multiplier',0);for(const id of ids)if(!project.demands.some(d=>d.id===id))throw new Error(`Unknown demand ${id}`);patch.demandMultipliers.push(...ids.map(demandId=>({demandId,multiplier})));}else throw new Error(`Unsupported hypothetical type ${type}`);const a=runScenarioCapacityAnalysis(project,patch);return {verdict:a.result.verdict,peakUtilizationPct:a.routing.peakUtilizationPct,violationCount:a.result.violations.length,criticalViolations:a.result.violations.slice(0,8).map(v=>({id:v.id,linkId:v.linkId,demandId:v.demandId,message:v.message}))};})});
  add({name:'add_plan_change',title:'Add visible ChangePlan change',description:'Adds a visible agent-attributed change to the current InfraTwin ChangePlan shared with the human. It never modifies the canonical network. target="selection" may be used only for a compatible current human selection.',inputSchema:schema({type:{type:'string',enum:['disable_link','enable_link','disable_node','enable_node','set_link_capacity','set_demand_bandwidth','add_demand','demand_growth']},target:{type:'string',enum:['selection']},linkId:{type:'string'},nodeId:{type:'string'},demandId:{type:'string'},capacityGbps:{type:'number',exclusiveMinimum:0},bandwidthGbps:{type:'number',minimum:0},demand:{type:'object'},demandIds:{type:'array',items:{type:'string'}},multiplier:{type:'number',minimum:0}},['type']),annotations:mut,execute:wrap(service,'add_plan_change',false,options,(input)=>service.addPlanChange(parsePlanChangeInput(input),'agent'),refresh)});
  add({name:'remove_plan_change',title:'Remove agent-visible ChangePlan change',description:'Removes a change from the same visible ChangePlan. Human locks are enforced; this does not modify the canonical network.',inputSchema:schema({changeId:{type:'string'}},['changeId']),annotations:mut,execute:wrap(service,'remove_plan_change',false,options,(input)=>service.removePlanChange(asString(input.changeId,'changeId'),'agent'),refresh)});
  add({name:'set_plan_constraints',title:'Update shared plan constraints',description:'Updates existing ChangePlan constraints visible to the human: target utilization, budget, N-1 requirement, or protected service classes. Evidence becomes stale.',inputSchema:schema({targetUtilizationPct:{type:'number',exclusiveMinimum:0,maximum:100},budgetCostUnits:{type:['number','null'],minimum:0},requireN1:{type:'boolean'},protectedServiceClassIds:{type:'array',items:{type:'string'}}}),annotations:mut,execute:wrap(service,'set_plan_constraints',false,options,(input)=>{const target='targetUtilizationPct'in input?inRange(asNumber(input.targetUtilizationPct,'targetUtilizationPct'),'targetUtilizationPct',Number.MIN_VALUE,100):undefined;const budget='budgetCostUnits'in input?(input.budgetCostUnits===null?null:inRange(asNumber(input.budgetCostUnits,'budgetCostUnits'),'budgetCostUnits',0)):undefined;const requireN1='requireN1'in input?asBoolean(input.requireN1,'requireN1'):undefined;const protectedIds='protectedServiceClassIds'in input?asStringArray(input.protectedServiceClassIds,'protectedServiceClassIds'):undefined;if(protectedIds){const classes=new Set(service.getProject().serviceClasses.map(item=>item.id));for(const id of protectedIds)if(!classes.has(id))throw new Error(`Unknown protected service class ${id}`);}let next=service.getChangePlan();if(target!==undefined)next=service.setPlanConstraint('targetUtilizationPct',target,'agent');if('budgetCostUnits'in input)next=service.setPlanConstraint('budgetCostUnits',budget??null,'agent');if(requireN1!==undefined)next=service.setPlanConstraint('requireN1',requireN1,'agent');if(protectedIds!==undefined)next=service.setPlanConstraint('protectedServiceClassIds',protectedIds,'agent');return next;},refresh)});
  add({name:'set_plan_restriction',title:'Add shared planning restriction',description:'Locks a link or node in the visible ChangePlan so agent/optimizer mutations cannot use it. Agents may add restrictions but cannot silently remove human locks.',inputSchema:schema({kind:{type:'string',enum:['link','node']},id:{type:'string'},target:{type:'string',enum:['selection']},locked:{type:'boolean',const:true}},['kind']),annotations:mut,execute:wrap(service,'set_plan_restriction',false,options,(input)=>{const kind=asString(input.kind,'kind');if(kind!=='link'&&kind!=='node')throw new Error('kind must be link or node.');const target=asSelectionTarget(input.target);if('locked'in input&&input.locked!==true)throw new Error('Agent restrictions may only set locked=true.');let id=target==='selection'?'':asString(input.id,'id');if(target==='selection'){const selection=service.getSelection();if(!selection||selection.kind!==kind)throw new Error(`Current selection must be a ${kind}.`);id=selection.id;}return service.setPlanRestriction(kind,id,true,'agent');},refresh)});
  add({name:'analyze_plan',title:'Analyze shared ChangePlan',description:'Runs deterministic analysis on the exact current visible ChangePlan, publishes the same result into the UI, and rejects stale publication if the human edits during execution.',inputSchema:schema(),annotations:mut,execute:wrap(service,'analyze_plan',false,options,(_i,e)=>service.analyzePlan(e?.signal),refresh)});
  add({name:'run_contingencies',title:'Run bounded N-1 on shared ChangePlan',description:'Runs bounded exact single-link contingencies on the current visible ChangePlan. Returns tested/eligible coverage truthfully; partial coverage is never represented as N-1 safe.',inputSchema:schema({maxScenarios:{type:'integer',minimum:1}}),annotations:mut,execute:wrap(service,'run_contingencies',false,options,(i,e)=>{const max=i.maxScenarios===undefined?undefined:asNumber(i.maxScenarios,'maxScenarios');if(max!==undefined&&(!Number.isInteger(max)||max<1))throw new Error('maxScenarios must be a positive integer.');return service.runContingencies(e?.signal,max);},refresh)});
  add({name:'verify_plan',title:'Verify current shared plan',description:'Deterministically verifies the current ChangePlan/proposal state and reports model/plan hashes, checked constraints, scenario coverage, and stale/partial state. Verification is not deployment.',inputSchema:schema(),annotations:mut,execute:wrap(service,'verify_plan',false,options,(_i,e)=>service.verifyPlan(e?.signal),refresh)});
  add({name:'inspect_violation',title:'Inspect current violation',description:'Read a targeted deterministic violation from the current failing analysis. Available only while failing evidence is current.',inputSchema:schema({violationId:{type:'string'}}),annotations:ro,execute:wrap(service,'inspect_violation',true,options,(i)=>service.inspectViolation(typeof i.violationId==='string'?i.violationId:undefined))});
  add({name:'focus_violation',title:'Show current violation to human',description:'Focus a current deterministic violation in the human Network workspace by selecting its relevant object/evidence. This changes presentation context only, not engineering truth.',inputSchema:schema({violationId:{type:'string'}}),annotations:{readOnlyHint:false,untrustedContentHint:true},execute:wrap(service,'focus_violation',false,options,(i)=>service.focusViolation(typeof i.violationId==='string'?i.violationId:undefined),refresh)});
  add({name:'find_bottlenecks',title:'Inspect bottleneck evidence',description:'Read deterministic min-cut bottleneck evidence for the current failing ChangePlan. Available only with current failing analysis.',inputSchema:schema(),annotations:ro,execute:wrap(service,'find_bottlenecks',true,options,()=>service.findBottlenecks())});
  add({name:'propose_mitigation',title:'Propose mitigation for shared plan',description:'Runs the current bounded mitigation optimizer against the shared ChangePlan, constraints, and human restrictions. It prefers the proven capacity-only formulation when sufficient, then can replan with bounded adaptive routing/design. Publishes a visible proposal but never applies the canonical network.',inputSchema:schema(),annotations:mut,execute:wrap(service,'propose_mitigation',false,options,(_i,e)=>service.generateMitigation(e?.signal),refresh)});
  add({name:'compare_mitigation_variants',title:'Compare bounded mitigation variants',description:'Generates a small deterministic nondominated set of verified adaptive design variants for the current failing ChangePlan. Results remain browser-session proposal state and never mutate the canonical network.',inputSchema:schema(),annotations:mut,execute:wrap(service,'compare_mitigation_variants',false,options,(_i,e)=>service.compareMitigationVariants(e?.signal),refresh)});
  add({name:'accept_proposal_change',title:'Accept one proposal into ChangePlan',description:'Marks one current agent proposal accepted and adds that proposal change to the visible ChangePlan. It still does not modify the canonical base network.',inputSchema:schema({proposalId:{type:'string'}},['proposalId']),annotations:mut,execute:wrap(service,'accept_proposal_change',false,options,(i)=>service.acceptProposalChange(asString(i.proposalId,'proposalId'),'agent'),refresh)});
  add({name:'reject_proposal_change',title:'Reject one proposal change',description:'Rejects one current proposal in the shared ChangePlan proposal state. It does not modify the canonical network.',inputSchema:schema({proposalId:{type:'string'}},['proposalId']),annotations:mut,execute:wrap(service,'reject_proposal_change',false,options,(i)=>service.rejectProposalChange(asString(i.proposalId,'proposalId'),'agent'),refresh)});
  add({name:'discard_proposal',title:'Discard current mitigation proposal',description:'Discards remaining pending optimizer proposals from the shared ChangePlan. It does not modify the canonical network.',inputSchema:schema(),annotations:mut,execute:wrap(service,'discard_proposal',false,options,()=>service.discardProposal('agent'),refresh)});
  return tools;
}
function parsePlanChangeInput(i:Record<string,unknown>):PlanChangeInput {const type=asString(i.type,'type'),target=asSelectionTarget(i.target);if(type==='disable_link'||type==='enable_link')return {type,linkId:asOptionalString(i.linkId,'linkId'),target};if(type==='disable_node'||type==='enable_node')return {type,nodeId:asOptionalString(i.nodeId,'nodeId'),target};if(type==='set_link_capacity')return {type,linkId:asOptionalString(i.linkId,'linkId'),target,capacityGbps:inRange(asNumber(i.capacityGbps,'capacityGbps'),'capacityGbps',Number.MIN_VALUE)};if(type==='set_demand_bandwidth')return {type,demandId:asOptionalString(i.demandId,'demandId'),target,bandwidthGbps:inRange(asNumber(i.bandwidthGbps,'bandwidthGbps'),'bandwidthGbps',0)};if(type==='demand_growth')return {type,demandIds:i.demandIds===undefined?undefined:asStringArray(i.demandIds,'demandIds'),target,multiplier:inRange(asNumber(i.multiplier,'multiplier'),'multiplier',0)};if(type==='add_demand'){if(!i.demand||typeof i.demand!=='object'||Array.isArray(i.demand))throw new Error('demand object is required.');return {type,demand:i.demand as never};}throw new Error(`Unsupported change type ${type}`);}

export async function registerCollaborativeTools(context:ModelContextLike,service:CollaborativeWorkspaceService,options:WebMCPRegistrationOptions={}):Promise<WebMCPRegistration>{
  const registrations=new Map<string,AbortController>();let disposed=false;let tools:Map<string,WebMCPTool>;let refreshTail:Promise<void>=Promise.resolve();
  const desired=()=>{const state=service.capabilityState();const names=new Set<string>(CORE_TOOL_NAMES);if(state.hasViolation)for(const n of VIOLATION_TOOL_NAMES)names.add(n);if(state.canProposeMitigation)for(const n of MITIGATION_TOOL_NAMES)names.add(n);if(state.canCompareMitigationVariants)for(const n of DESIGN_TOOL_NAMES)names.add(n);if(state.canDecideProposal)for(const n of PROPOSAL_TOOL_NAMES)names.add(n);return names;};
  const applyRefresh=async()=>{if(disposed)return;const want=desired();for(const [name,c] of [...registrations])if(!want.has(name)){c.abort();registrations.delete(name);}for(const name of want)if(!registrations.has(name)){const tool=tools.get(name);if(!tool)continue;const c=new AbortController();try{await context.registerTool(tool,{signal:c.signal});if(disposed)c.abort();else registrations.set(name,c);}catch(error){c.abort();throw error;}}options.onToolSetChanged?.([...registrations.keys()].sort());};
  const refresh=()=>{const run=refreshTail.then(applyRefresh,applyRefresh);refreshTail=run.catch(()=>{});return run;};
  tools=buildTools(service,options,refresh);
  await refresh();
  return {refresh:async()=>{await refresh();return [...registrations.keys()].sort();},dispose:()=>{disposed=true;for(const c of registrations.values())c.abort();registrations.clear();options.onToolSetChanged?.([]);},getRegisteredNames:()=>[...registrations.keys()].sort()};
}

/** Compatibility helper for low-level tests; registers the complete current state and returns one disposer. */
export async function registerBaseTools(context:ModelContextLike,service:CollaborativeWorkspaceService,options:WebMCPRegistrationOptions={}):Promise<()=>void>{const reg=await registerCollaborativeTools(context,service,options);return()=>reg.dispose();}
