import { test, expect, type Page } from '@playwright/test';
import { createLevel4ReplanReference } from '../packages/scenarios/src/index.ts';
import { executeTool, openHarnessedWorkbench } from './webmcp-harness';
async function open(page: Page) { await page.goto('/'); await expect(page.getByTestId('topology-canvas')).toBeVisible(); }
async function importReference(page: Page) { await page.getByTestId('import-json').click(); await page.getByRole('button',{name:'Canonical JSON'}).click(); await page.getByTestId('json-import-file').setInputFiles({name:'level4a-replan-reference.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(createLevel4ReplanReference()))}); await expect(page.getByTestId('import-review')).toContainText('4'); await page.getByTestId('open-imported-network').click(); await expect(page.getByTestId('topology-link-X')).toBeVisible(); await page.getByTestId('plan-constraints').locator('summary').click(); await page.getByTestId('allow-routing-changes').check(); await page.getByTestId('plan-constraints').locator('summary').click(); }
async function analyzeFail(page: Page){await page.getByTestId('analyze-plan').click();await expect(page.getByTestId('verdict')).toHaveText('FAIL');}
async function lockXAndReplan(page: Page){await analyzeFail(page);await page.getByTestId('run-optimizer').click();await expect(page.getByTestId('candidate-proposals')).toContainText('X',{timeout:30000});await expect(page.getByTestId('candidate-proposals')).toContainText('15 Gbps');await page.getByTestId('topology-link-X').click();await page.getByTestId('lock-link-X').check();await expect(page.getByTestId('candidate-proposals')).toContainText(/stale.*needs replanning/i);await page.getByTestId('analyze-plan').click();await expect(page.getByTestId('verdict')).toHaveText('FAIL');await page.getByTestId('run-optimizer').click();await expect(page.getByTestId('candidate-proposals')).toContainText('Y',{timeout:30000});await expect(page.getByTestId('candidate-proposals')).not.toContainText('Set X capacity');await expect(page.getByTestId('network-design-summary')).toContainText(/Cost\s*8/i);await expect(page.getByTestId('network-design-summary')).toContainText(/verified/i);}
async function selectDemand(page:Page,demandId:string){await page.getByTestId('topology-search').fill(demandId);await page.getByTestId(`search-result-demand-${demandId}`).click();await expect(page.getByTestId(`demand-inspector-${demandId}`)).toBeVisible();}
test('Level 4A 1 — capacity-only X cost 5 becomes verified adaptive Y cost 8 after the human protects X',async({page})=>{await open(page);await importReference(page);await lockXAndReplan(page);await expect(page.getByTestId('proposal-Y')).toContainText('5 Gbps');});
test('Level 4A 2 — selected demand explains default SSP route versus proposed 66.7/33.3 adaptive allocation',async({page})=>{await open(page);await importReference(page);await lockXAndReplan(page);await selectDemand(page,'D1');await expect(page.getByTestId('demand-inspector-D1')).toContainText(/X \/ BD|BD \/ X/);const proposed=page.getByTestId('selected-demand-design-routes');await expect(proposed).toContainText('66.7%');await expect(proposed).toContainText('33.3%');await expect(proposed).toContainText('X → BD');await expect(proposed).toContainText('AC → Y');});
test('Level 4A 3 — Plans exposes the true verified Pareto frontier and Network follows selected variant',async({page})=>{await open(page);await importReference(page);await page.getByTestId('topology-link-X').click();await page.getByTestId('lock-link-X').check();await analyzeFail(page);await page.getByTestId('nav-plans').click();await page.getByTestId('compare-design-variants').click();const rows=page.locator('[data-testid^="design-variant-design:"]');await expect(rows).toHaveCount(3,{timeout:30000});await expect(page.getByTestId('design-variant-table')).toContainText('8');await expect(page.getByTestId('design-variant-table')).toContainText('12');await expect(page.getByTestId('design-variant-table')).toContainText('16');await rows.nth(1).click();await page.getByTestId('nav-network').click();await expect(page.getByTestId('network-design-summary')).toContainText(/Cost\s*12/i);});
test('Level 4A 4 — semantic human edit cancels/invalidates in-flight variant generation and no stale frontier publishes',async({page})=>{await open(page);await importReference(page);await page.getByTestId('topology-link-X').click();await page.getByTestId('lock-link-X').check();await analyzeFail(page);await page.getByTestId('nav-plans').click();await page.getByTestId('compare-design-variants').click();await page.getByTestId('nav-network').click();await page.getByTestId('plan-constraints').locator('summary').click();await page.getByTestId('constraint-max-candidate-paths').selectOption('6');await page.getByTestId('nav-plans').click();await expect(page.locator('[data-testid^="design-variant-design:"]')).toHaveCount(0,{timeout:30000});});
test('Level 4A 5 — WebMCP propose_mitigation observes human lock and transparently returns the adaptive alternative',async({page})=>{await openHarnessedWorkbench(page);await importReference(page);const analysis1=await executeTool(page,'analyze_plan');expect(analysis1.result.verdict).toBe('FAIL');const first=await executeTool(page,'propose_mitigation');expect(first.result.mode).toBe('capacity-only');expect(first.result.objective).toBe(5);await page.getByTestId('topology-link-X').click();await page.getByTestId('lock-link-X').check();const inspected=await executeTool(page,'inspect_plan');expect(inspected.result.restrictions.lockedLinkIds).toContain('X');await executeTool(page,'analyze_plan');const second=await executeTool(page,'propose_mitigation');expect(second.result.mode).toBe('adaptive-design');expect(second.result.objective).toBe(8);expect(second.result.verification).toBe('verified');await expect(page.getByTestId('candidate-proposals')).toContainText('Y');await expect(page.getByTestId('network-design-summary')).toContainText(/Cost\s*8/i);});
