export interface NodeModel { id: string; name: string; region?: string; type?: string; available?: boolean; x?: number; y?: number; }
export interface LinkModel { id: string; source: string; target: string; bidirectional?: boolean; capacityGbps: number; latencyMs?: number; weight: number; available?: boolean; upgradeOptions?: Array<{ capacityGbps: number; cost: number }>; }
export interface DemandModel { id: string; name?: string; source: string; target: string; bandwidthGbps: number; serviceClassId: string; }
export interface ServiceClassModel { id: string; name: string; priority: number; maxUtilizationPct: number; allowShedding?: boolean; }
export interface RoutingProfile { mode: 'single-shortest-path' | 'ecmp'; }
export interface NetworkProject { schemaVersion: '0.1'; id: string; name: string; nodes: NodeModel[]; links: LinkModel[]; demands: DemandModel[]; serviceClasses: ServiceClassModel[]; routingProfile: RoutingProfile; metadata?: Record<string, unknown>; }
export interface ValidationResult { valid: boolean; errors: string[]; }
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const nonEmptyString = (value: unknown): value is string => typeof value === 'string' && value.trim().length > 0;
const finiteNumber = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);
export function validateNetworkProject(value: unknown): ValidationResult {
  const errors: string[] = [];
  if (!isRecord(value)) return { valid: false, errors: ['project must be an object'] };
  if (value.schemaVersion !== '0.1') errors.push('schemaVersion must equal 0.1');
  if (!nonEmptyString(value.id)) errors.push('id must be a non-empty string');
  if (!nonEmptyString(value.name)) errors.push('name must be a non-empty string');
  if (!Array.isArray(value.nodes)) errors.push('nodes must be an array');
  if (!Array.isArray(value.links)) errors.push('links must be an array');
  if (!Array.isArray(value.demands)) errors.push('demands must be an array');
  if (!Array.isArray(value.serviceClasses)) errors.push('serviceClasses must be an array');
  if (!isRecord(value.routingProfile) || !['single-shortest-path', 'ecmp'].includes(String(value.routingProfile.mode))) errors.push('routingProfile.mode must be single-shortest-path or ecmp');
  if (errors.length) return { valid: false, errors };
  const nodes = value.nodes as unknown[]; const links = value.links as unknown[]; const demands = value.demands as unknown[]; const classes = value.serviceClasses as unknown[];
  const nodeIds = new Set<string>(); const linkIds = new Set<string>(); const demandIds = new Set<string>(); const classIds = new Set<string>();
  nodes.forEach((node, index) => { if (!isRecord(node)) return errors.push(`nodes[${index}] must be an object`); if (!nonEmptyString(node.id)) errors.push(`nodes[${index}].id must be non-empty`); else if (nodeIds.has(node.id)) errors.push(`duplicate node id ${node.id}`); else nodeIds.add(node.id); if (!nonEmptyString(node.name)) errors.push(`nodes[${index}].name must be non-empty`); if (node.available !== undefined && typeof node.available !== 'boolean') errors.push(`nodes[${index}].available must be boolean`); if (node.x !== undefined && !finiteNumber(node.x)) errors.push(`nodes[${index}].x must be finite`); if (node.y !== undefined && !finiteNumber(node.y)) errors.push(`nodes[${index}].y must be finite`); });
  classes.forEach((serviceClass, index) => { if (!isRecord(serviceClass)) return errors.push(`serviceClasses[${index}] must be an object`); if (!nonEmptyString(serviceClass.id)) errors.push(`serviceClasses[${index}].id must be non-empty`); else if (classIds.has(serviceClass.id)) errors.push(`duplicate service class id ${serviceClass.id}`); else classIds.add(serviceClass.id); if (!nonEmptyString(serviceClass.name)) errors.push(`serviceClasses[${index}].name must be non-empty`); if (!Number.isInteger(serviceClass.priority) || Number(serviceClass.priority) < 0) errors.push(`serviceClasses[${index}].priority must be a non-negative integer`); if (!finiteNumber(serviceClass.maxUtilizationPct) || Number(serviceClass.maxUtilizationPct) <= 0 || Number(serviceClass.maxUtilizationPct) > 100) errors.push(`serviceClasses[${index}].maxUtilizationPct must be in (0,100]`); });
  links.forEach((link, index) => { if (!isRecord(link)) return errors.push(`links[${index}] must be an object`); if (!nonEmptyString(link.id)) errors.push(`links[${index}].id must be non-empty`); else if (linkIds.has(link.id)) errors.push(`duplicate link id ${link.id}`); else linkIds.add(link.id); if (!nonEmptyString(link.source) || !nodeIds.has(String(link.source))) errors.push(`links[${index}].source must reference a node`); if (!nonEmptyString(link.target) || !nodeIds.has(String(link.target))) errors.push(`links[${index}].target must reference a node`); if (!finiteNumber(link.capacityGbps) || Number(link.capacityGbps) <= 0) errors.push(`links[${index}].capacityGbps must be > 0`); if (!finiteNumber(link.weight) || Number(link.weight) < 0) errors.push(`links[${index}].weight must be >= 0`); if (link.bidirectional !== undefined && typeof link.bidirectional !== 'boolean') errors.push(`links[${index}].bidirectional must be boolean`); if (link.available !== undefined && typeof link.available !== 'boolean') errors.push(`links[${index}].available must be boolean`); });
  demands.forEach((demand, index) => { if (!isRecord(demand)) return errors.push(`demands[${index}] must be an object`); if (!nonEmptyString(demand.id)) errors.push(`demands[${index}].id must be non-empty`); else if (demandIds.has(demand.id)) errors.push(`duplicate demand id ${demand.id}`); else demandIds.add(demand.id); if (!nonEmptyString(demand.source) || !nodeIds.has(String(demand.source))) errors.push(`demands[${index}].source must reference a node`); if (!nonEmptyString(demand.target) || !nodeIds.has(String(demand.target))) errors.push(`demands[${index}].target must reference a node`); if (!finiteNumber(demand.bandwidthGbps) || Number(demand.bandwidthGbps) < 0) errors.push(`demands[${index}].bandwidthGbps must be >= 0`); if (!nonEmptyString(demand.serviceClassId) || !classIds.has(String(demand.serviceClassId))) errors.push(`demands[${index}].serviceClassId must reference a service class`); });
  return { valid: errors.length === 0, errors };
}
export function assertValidNetworkProject(value: unknown): asserts value is NetworkProject { const result = validateNetworkProject(value); if (!result.valid) throw new Error(`Invalid network project: ${result.errors.join('; ')}`); }
export function cloneProject(project: NetworkProject): NetworkProject { return JSON.parse(JSON.stringify(project)) as NetworkProject; }
function stableValue(value: unknown): unknown { if (Array.isArray(value)) return value.map(stableValue); if (isRecord(value)) return Object.keys(value).sort().reduce<Record<string, unknown>>((out, key) => { out[key] = stableValue(value[key]); return out; }, {}); return value; }
export function stableStringify(value: unknown): string { return JSON.stringify(stableValue(value)); }
export function modelHash(project: NetworkProject): string { const text = stableStringify(project); let hash = 0x811c9dc5; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 0x01000193) >>> 0; } return `fnv1a32:${hash.toString(16).padStart(8, '0')}`; }
