import { useEffect, useState } from 'react';
import type { CandidateLinkOption, ChangePlan, NetworkProject, PlanChange, PlanConstraints } from '@infratwin/model';
import { describePlanChange } from '@infratwin/model';
import { CandidateProposalList } from './candidate-proposal-list';
import { DemandPlanEditor } from './demand-plan-editor';
import { SearchableSelect } from './searchable-select';

interface Props {
  project: NetworkProject; plan: ChangePlan; trafficEditorOpen: boolean; onTrafficEditorOpenChange: (open: boolean) => void;
  onRenamePlan: (name: string) => void; onRemoveChange: (id: string) => void;
  onSetConstraint: <K extends keyof PlanConstraints>(key: K, value: PlanConstraints[K]) => void;
  onSetBandwidth: (demandId: string, bandwidthGbps: number) => void;
  onAddDemand: (input: { name: string; source: string; target: string; bandwidthGbps: number; serviceClassId: string }) => void;
  onAddGrowth: (demandIds: string[], multiplier: number) => void;
  onAcceptProposal: (id: string) => void; onRejectProposal: (id: string) => void; onAcceptAll: () => void; onDiscardCandidate: () => void;
  onVerifyProposal?: () => void; candidateStale?: boolean;
}

export function ChangePlanPanel(props: Props) {
  const { project, plan } = props;
  const [planNameDraft, setPlanNameDraft] = useState(plan.name);
  const [renaming, setRenaming] = useState(false);
  const [candidateLinkDraft, setCandidateLinkDraft] = useState<CandidateLinkOption>({ id: '', source: project.nodes[0]?.id ?? '', target: project.nodes[1]?.id ?? project.nodes[0]?.id ?? '', capacityGbps: 10, weight: 1, cost: 10 });
  useEffect(() => { setPlanNameDraft(plan.name); setRenaming(false); }, [plan.id, plan.name]);
  useEffect(() => { if (!project.nodes.some((node) => node.id === candidateLinkDraft.source)) setCandidateLinkDraft((current) => ({ ...current, source: project.nodes[0]?.id ?? '' })); if (!project.nodes.some((node) => node.id === candidateLinkDraft.target)) setCandidateLinkDraft((current) => ({ ...current, target: project.nodes[1]?.id ?? project.nodes[0]?.id ?? '' })); }, [project.id, project.nodes, candidateLinkDraft.source, candidateLinkDraft.target]);
  const pending = plan.proposals.filter((proposal) => proposal.state === 'pending').length;
  const lockCount = plan.restrictions.lockedLinkIds.length + plan.restrictions.lockedNodeIds.length;
  const avoidanceCount = plan.restrictions.forbiddenRoutingLinkIds.length + plan.restrictions.forbiddenRoutingNodeIds.length;
  const visibleChangeSummary = (item: PlanChange) => item.type === 'demand_growth' && item.target.ids.length > 4 ? `Grow ${item.target.ids.length} demands by ${Math.round((item.payload.multiplier - 1) * 1000) / 10}%` : describePlanChange(item);
  const changeProvenance = (changeId: string, actor: 'human' | 'agent') => {
    if (actor === 'human') return 'Human';
    const proposal = plan.proposals.find((item) => item.change.id === changeId && item.state === 'accepted');
    const humanAccepted = proposal && plan.history.some((event) => event.action === 'accepted_proposal' && event.actor === 'human' && event.relatedId === proposal.id);
    return humanAccepted ? 'Agent · accepted by human' : 'Agent';
  };
  const saveName=()=>{const next=planNameDraft.trim(); if(next && next!==plan.name)props.onRenamePlan(next); else setPlanNameDraft(plan.name); setRenaming(false);};
  const nodeOptions=project.nodes.map((node)=>({value:node.id,label:node.name ? `${node.name} · ${node.id}`:node.id,secondary:node.region}));
  const candidateDisabledReason=!candidateLinkDraft.id.trim()?'Enter a unique candidate-link ID.':candidateLinkDraft.source===candidateLinkDraft.target?'Source and target must differ.':'';

  return <aside id="change-plan-panel" className="plan-panel" data-testid="change-plan-panel" aria-label="Current ChangePlan">
    <div className="plan-panel-header"><div className="plan-title-block"><span className="section-kicker">ChangePlan</span>{renaming ? <input autoFocus data-testid="plan-name" value={planNameDraft} aria-label="ChangePlan name" onChange={(event)=>setPlanNameDraft(event.target.value)} onBlur={saveName} onKeyDown={(event)=>{if(event.key==='Enter')saveName(); if(event.key==='Escape'){setPlanNameDraft(plan.name);setRenaming(false);}}}/> : <button type="button" className="plan-title-button" data-testid="plan-name" title={plan.name} onClick={()=>setRenaming(true)}><strong>{plan.name}</strong><span aria-hidden="true">✎</span></button>}</div><span className={`plan-status ${plan.status}`}>{plan.status}</span></div>

    <section className="compact-section" data-testid="plan-change-list"><div className="section-row"><span>Planned changes</span><strong>{plan.changes.length}</strong></div>{plan.changes.length===0?<p className="muted compact-copy">No planned changes yet.</p>:<div className="compact-list">{plan.changes.map((item)=><div className={`plan-change-row actor-${item.actor}`} key={item.id}><div><strong>{visibleChangeSummary(item)}</strong><small><span className={`actor-chip ${item.actor}`}>{changeProvenance(item.id,item.actor)}</span></small></div><button className="remove-row" aria-label={`Remove ${visibleChangeSummary(item)}`} data-testid={`remove-plan-change-${item.id}`} onClick={()=>props.onRemoveChange(item.id)}>Remove</button></div>)}</div>}</section>

    <details className="compact-disclosure" data-testid="plan-constraints"><summary><span>Planning constraints</span><strong>{plan.constraints.targetUtilizationPct}% target · {plan.constraints.budgetCostUnits===null?'no budget cap':`budget ${plan.constraints.budgetCostUnits}`}</strong></summary><div className="compact-disclosure-body constraint-groups">
      <section className="constraint-group"><span className="mini-label">Planning target</span><div className="compact-form"><label>Target utilization %<input data-testid="constraint-target-utilization" type="number" min="0.1" max="100" step="1" value={plan.constraints.targetUtilizationPct} onChange={(event)=>props.onSetConstraint('targetUtilizationPct',Number(event.target.value))}/></label><label>Budget (cost units)<input data-testid="constraint-budget" type="number" min="0" step="1" value={plan.constraints.budgetCostUnits??''} placeholder="No budget cap" onChange={(event)=>props.onSetConstraint('budgetCostUnits',event.target.value===''?null:Number(event.target.value))}/></label><label className="check-row"><input data-testid="constraint-require-n1" type="checkbox" checked={plan.constraints.requireN1} onChange={(event)=>props.onSetConstraint('requireN1',event.target.checked)}/>Require N-1 resilience</label></div></section>
      <section className="constraint-group"><span className="mini-label">Allowed changes</span><div className="checkbox-grid"><label className="check-row"><input data-testid="allow-capacity-upgrades" type="checkbox" checked={plan.constraints.allowedMitigationActions.capacityUpgrades} onChange={(event)=>props.onSetConstraint('allowedMitigationActions',{...plan.constraints.allowedMitigationActions,capacityUpgrades:event.target.checked})}/>Upgrade capacity</label><label className="check-row"><input data-testid="allow-routing-changes" type="checkbox" checked={plan.constraints.allowedMitigationActions.routingChanges} onChange={(event)=>props.onSetConstraint('allowedMitigationActions',{...plan.constraints.allowedMitigationActions,routingChanges:event.target.checked})}/>Change routing</label><label className="check-row"><input data-testid="allow-new-links" type="checkbox" checked={plan.constraints.allowedMitigationActions.newLinks} onChange={(event)=>props.onSetConstraint('allowedMitigationActions',{...plan.constraints.allowedMitigationActions,newLinks:event.target.checked})}/>Add declared links</label></div></section>
      <section className="constraint-group"><span className="mini-label">Routing restrictions</span><label>Candidate paths per demand<select data-testid="constraint-max-candidate-paths" value={plan.constraints.maxCandidatePaths} onChange={(event)=>props.onSetConstraint('maxCandidatePaths',Number(event.target.value))}>{[1,2,3,4,5,6,7,8].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><span className="mini-label nested">Protected services</span><div className="checkbox-grid">{project.serviceClasses.map((item)=><label className="check-row" key={item.id}><input data-testid={`protected-class-${item.id}`} type="checkbox" checked={plan.constraints.protectedServiceClassIds.includes(item.id)} onChange={(event)=>props.onSetConstraint('protectedServiceClassIds',event.target.checked?[...new Set([...plan.constraints.protectedServiceClassIds,item.id])]:plan.constraints.protectedServiceClassIds.filter((id)=>id!==item.id))}/>{item.name}</label>)}</div></section>
      {plan.constraints.allowedMitigationActions.newLinks&&<section className="constraint-group candidate-link-editor" data-testid="candidate-link-editor"><span className="mini-label">Declared candidate links</span>{plan.constraints.candidateLinkOptions.length>0&&<div className="compact-list">{plan.constraints.candidateLinkOptions.map((item)=><div key={item.id} className="plan-change-row"><div><strong>{item.id}: {item.source} ↔ {item.target}</strong><small>{item.capacityGbps} Gbps · weight {item.weight} · cost {item.cost}</small></div><button className="remove-row" type="button" aria-label={`Remove candidate ${item.id}`} onClick={()=>props.onSetConstraint('candidateLinkOptions',plan.constraints.candidateLinkOptions.filter((candidate)=>candidate.id!==item.id))}>Remove</button></div>)}</div>}<div className="compact-form"><label>ID<input data-testid="candidate-link-id" value={candidateLinkDraft.id} onChange={(event)=>setCandidateLinkDraft((current)=>({...current,id:event.target.value}))}/></label><SearchableSelect label="Source" value={candidateLinkDraft.source} options={nodeOptions} onChange={(source)=>setCandidateLinkDraft((current)=>({...current,source}))}/><SearchableSelect label="Target" value={candidateLinkDraft.target} options={nodeOptions} onChange={(target)=>setCandidateLinkDraft((current)=>({...current,target}))}/><label>Capacity (Gbps)<input data-testid="candidate-link-capacity" type="number" min="0.1" step="1" value={candidateLinkDraft.capacityGbps} onChange={(event)=>setCandidateLinkDraft((current)=>({...current,capacityGbps:Number(event.target.value)}))}/></label><label>Weight<input data-testid="candidate-link-weight" type="number" min="0.1" step="0.1" value={candidateLinkDraft.weight} onChange={(event)=>setCandidateLinkDraft((current)=>({...current,weight:Number(event.target.value)}))}/></label><label>Cost<input data-testid="candidate-link-cost" type="number" min="0" step="1" value={candidateLinkDraft.cost} onChange={(event)=>setCandidateLinkDraft((current)=>({...current,cost:Number(event.target.value)}))}/></label></div><button type="button" data-testid="add-candidate-link" disabled={Boolean(candidateDisabledReason)} title={candidateDisabledReason||undefined} onClick={()=>{const next={...candidateLinkDraft,id:candidateLinkDraft.id.trim()};props.onSetConstraint('candidateLinkOptions',[...plan.constraints.candidateLinkOptions.filter((item)=>item.id!==next.id),next]);setCandidateLinkDraft((current)=>({...current,id:''}));}}>Declare candidate link</button>{candidateDisabledReason&&<small className="control-help">{candidateDisabledReason}</small>}</section>}
    </div></details>

    <details className="compact-disclosure" open={props.trafficEditorOpen} onToggle={(event)=>props.onTrafficEditorOpenChange((event.currentTarget as HTMLDetailsElement).open)}><summary><span>Planned traffic changes</span><strong>{plan.changes.filter((item)=>item.type==='set_demand_bandwidth'||item.type==='add_demand'||item.type==='demand_growth').length} planned</strong></summary><div className="compact-disclosure-body"><DemandPlanEditor project={project} plan={plan} onSetBandwidth={props.onSetBandwidth} onAddDemand={props.onAddDemand} onAddGrowth={props.onAddGrowth}/></div></details>

    <section className="compact-section" data-testid="plan-restrictions"><div className="section-row"><span>Human restrictions</span><strong>{lockCount+avoidanceCount}</strong></div><p className="muted compact-copy">{lockCount||avoidanceCount?`${lockCount} modification lock${lockCount===1?'':'s'} · ${avoidanceCount} routing avoidance rule${avoidanceCount===1?'':'s'}`:'No human restrictions yet.'}</p></section>

    {pending>0&&<section className="compact-section proposal-section"><div className="section-row"><span>Proposed changes</span><strong>{pending} pending</strong></div><p className="compact-copy proposal-boundary">Proposals are not applied to the base network. Human review is required.</p>{props.onVerifyProposal&&<button type="button" className="wide" data-testid="verify-candidate" disabled={props.candidateStale} title={props.candidateStale?'Proposal is stale after the latest plan edit. Find mitigation again.':undefined} onClick={props.onVerifyProposal}>{props.candidateStale?'Proposal stale · re-run mitigation':'Verify proposal'}</button>}<CandidateProposalList plan={plan} onAccept={props.onAcceptProposal} onReject={props.onRejectProposal} onAcceptAll={props.onAcceptAll} onDiscard={props.onDiscardCandidate}/></section>}
  </aside>;
}
