'use client';

import type { CapacityAnalysis } from '@infratwin/evidence';
import { ANALYSIS_TABS, type AnalysisTab } from '../lib/application-shell';

function pct(value:number){return `${Math.round(value*10)/10}%`;}
function gbps(value:number){return `${Math.round(value*100)/100} Gbps`;}
function allRouteLinks(route:CapacityAnalysis['routing']['routes'][number]|undefined):string[]{return route?Object.keys(route.linkFractions).filter((linkId)=>route.linkFractions[linkId]>0).sort():[];}

export function useWorkbenchStage6(scope:any){
  const { project, plan, ephemeralPatch, setEphemeralPatch, contingencies, n1Fresh, analysisStatus, lastAnalysisExecution, lastAnalysisRuntimeMs, resilienceStatus, resilienceMessage, progressLabel, executionProfile, authority, primaryFailure, analysisStatusLabel, analysis, analysisAuthoritative, selectedDesignVariant, setActiveView, setAnalysisTab, setRightPanelCollapsed, selectedCanonicalLink, selectedCanonicalNode, selectedCanonicalDemand, selectedSnapshotLink, selectedRoute, selectedDesignRoutes, plannedOutageLinkIds, plannedChangedLinkIds, plannedOutageNodeIds, plannedChangedNodeIds, lockedLinkIds, lockedNodeIds, runWorkspaceAction, workspaceService, inspectorCapacityDraft, setInspectorCapacityDraft, handleLinkAvailability, handleLinkCapacity, setSettingsLinkId, handleNodeAvailability, setTrafficEditorOpen, setLeftPanelCollapsed, ephemeralRef, optimizerStatus, optimizerMessage }=scope;
  const currentAnalysisVisible = Boolean(ephemeralPatch) || (analysisAuthoritative && (authority === 'PASS' || authority === 'FAIL'));
  const renderPlanResultSummary=()=> <section data-testid="plan-analysis-status" className="plan-state-stack" aria-label="Current plan and proposed design status">
    <div className={`plan-result-summary current-state result-${authority.toLowerCase()}`} data-testid="current-plan-state"><div className="state-card-heading"><div><span className="section-kicker">{ephemeralPatch?'Counterexample replay':'Current plan'}</span><strong data-testid="verdict">{ephemeralPatch?analysis.result.verdict:authority}</strong></div><span className="state-kind">{ephemeralPatch?'Replay evidence':'Deterministic evidence'}</span></div><p>{ephemeralPatch?`${ephemeralPatch.name} · ${analysis.result.violations.length} modeled violation${analysis.result.violations.length===1?'':'s'}.`:analysisStatusLabel}</p>{currentAnalysisVisible&&analysis.result.violations.length>0&&<div data-testid="evidence-panel" className="current-evidence-summary">{analysis.result.violations.slice(0,3).map((item:any)=><small key={item.id}>{item.message}</small>)}</div>}{!ephemeralPatch&&authority==='FAIL'&&primaryFailure&&<small>Primary issue: {primaryFailure}</small>}{analysisStatus==='running'&&<div className="operation-progress"><span className="spinner" aria-hidden="true"/><strong>Analyzing ChangePlan</strong><small>{scope.analysisMessage}</small></div>}{analysisStatus!=='idle'&&analysisStatus!=='running'&&<small data-testid="capacity-analysis-status">Analysis {analysisStatus} · {lastAnalysisExecution??executionProfile.mode}{lastAnalysisRuntimeMs===null?'':` · ${lastAnalysisRuntimeMs} ms on this browser run`}</small>}{resilienceStatus!=='idle'&&<small data-testid="resilience-status">N-1 {resilienceStatus} · {progressLabel} · {resilienceMessage}</small>}{contingencies&&n1Fresh&&<small data-testid="resilience-evidence">{contingencies.completedScenarios}/{contingencies.totalEligibleScenarios} failures tested · {contingencies.status.toUpperCase()} · {contingencies.result.metrics.failingScenarios} failing</small>}<button type="button" className="text-action" onClick={()=>{setActiveView('analysis');setAnalysisTab('summary');}}>Inspect analysis</button></div>
    {selectedDesignVariant&&<div className={`proposed-design-summary verification-${selectedDesignVariant.verification.status}`} data-testid="network-design-summary"><div className="state-card-heading"><div><span className="section-kicker">Proposed design</span><strong>{selectedDesignVariant.verification.status.toUpperCase()}</strong></div><span className="state-kind">Awaiting human review</span></div><dl className="proposal-metrics"><div><dt>Peak</dt><dd>{pct(selectedDesignVariant.peakUtilizationPct)}</dd></div><div><dt>Cost</dt><dd>{selectedDesignVariant.totalCost}</dd></div></dl><small>{selectedDesignVariant.selectedUpgrades.length?`${selectedDesignVariant.selectedUpgrades.length} capacity upgrade${selectedDesignVariant.selectedUpgrades.length===1?'':'s'}`:'No capacity upgrades'} · {selectedDesignVariant.evidence.routingAllocationSummary.length} routing change{selectedDesignVariant.evidence.routingAllocationSummary.length===1?'':'s'}</small><p className="proposal-boundary">Verified proposal · not applied to the base network.</p></div>}
    {optimizerStatus==='running'&&<div className="operation-progress optimizer-progress" data-testid="optimizer-progress"><span className="spinner" aria-hidden="true"/><div><strong>Preparing mitigation</strong><small>{optimizerMessage}</small></div></div>}
  </section>;

  const renderInspector=()=> <aside id="object-inspector" className="workspace-pane inspector-pane" data-testid="object-inspector" aria-label="Inspector">
    {renderPlanResultSummary()}
    <div className="inspector-header"><span className="section-kicker">Inspector</span><button type="button" className="icon-button" aria-label="Collapse inspector" title="Collapse inspector" onClick={()=>setRightPanelCollapsed(true)}>×</button></div>
    {!selectedCanonicalLink&&!selectedCanonicalNode&&!selectedCanonicalDemand&&<section className="inspector-section inspector-empty" data-testid="network-inspector-empty"><h3>Nothing selected</h3><p className="muted compact-copy">Select a link, node, or demand to inspect its current and planned state.</p></section>}
    {selectedCanonicalLink&&<section className="inspector-section" data-testid={`link-inspector-${selectedCanonicalLink.id}`}><div className="inspector-title"><div><span>Link</span><h3>{selectedCanonicalLink.source} ↔ {selectedCanonicalLink.target}</h3></div><strong className="mono">{selectedCanonicalLink.id}</strong></div><dl className="compact-metrics"><div><dt>Capacity</dt><dd>{gbps(selectedSnapshotLink?.capacityGbps??selectedCanonicalLink.capacityGbps)}</dd></div><div><dt>Load</dt><dd>{currentAnalysisVisible?gbps(analysis.routing.linkLoadsGbps[selectedCanonicalLink.id]??0):'—'}</dd></div><div><dt>Utilization</dt><dd>{currentAnalysisVisible?pct(analysis.routing.linkUtilizationPct[selectedCanonicalLink.id]??0):'Not analyzed'}</dd></div><div><dt>Availability</dt><dd>{selectedSnapshotLink?.available===false?'Unavailable':'Available'}</dd></div><div><dt>Plan state</dt><dd>{plannedOutageLinkIds.has(selectedCanonicalLink.id)?'Planned outage':plannedChangedLinkIds.has(selectedCanonicalLink.id)?'Modified':'Unchanged'}</dd></div></dl><div className="inspector-actions"><button type="button" data-testid={`plan-link-outage-${selectedCanonicalLink.id}`} onClick={()=>handleLinkAvailability(selectedCanonicalLink.id,plannedOutageLinkIds.has(selectedCanonicalLink.id))}>{plannedOutageLinkIds.has(selectedCanonicalLink.id)?'Remove planned outage':'Add outage'}</button><label className="check-action"><input type="checkbox" data-testid={`lock-link-${selectedCanonicalLink.id}`} checked={lockedLinkIds.has(selectedCanonicalLink.id)} onChange={(event)=>runWorkspaceAction(()=>{workspaceService.setPlanRestriction('link',selectedCanonicalLink.id,event.target.checked,'human');})}/>Lock link</label><label className="check-action"><input type="checkbox" data-testid={`avoid-link-${selectedCanonicalLink.id}`} checked={(plan.restrictions.forbiddenRoutingLinkIds??[]).includes(selectedCanonicalLink.id)} onChange={(event)=>runWorkspaceAction(()=>{workspaceService.setRoutingRestriction('link',selectedCanonicalLink.id,event.target.checked,'human');})}/>Avoid in proposed routing</label></div><div className="inline-edit"><label>Planned capacity (Gbps)<input data-testid="link-capacity-input" type="number" min="0.1" step="1" value={inspectorCapacityDraft??''} onChange={(event)=>setInspectorCapacityDraft(event.target.value===''?null:Number(event.target.value))}/></label><button type="button" data-testid={`plan-link-capacity-${selectedCanonicalLink.id}`} disabled={inspectorCapacityDraft===null} title={inspectorCapacityDraft===null?'Enter a planned capacity first.':undefined} onClick={()=>inspectorCapacityDraft!==null&&handleLinkCapacity(selectedCanonicalLink.id,inspectorCapacityDraft)}>Apply</button></div><button type="button" className="text-action" onClick={()=>{setSettingsLinkId(selectedCanonicalLink.id);setActiveView('settings');}}>Edit upgrade catalog</button></section>}
    {selectedCanonicalNode&&<section className="inspector-section" data-testid={`node-inspector-${selectedCanonicalNode.id}`}><div className="inspector-title"><div><span>Node</span><h3>{selectedCanonicalNode.name??selectedCanonicalNode.id}</h3></div><strong className="mono">{selectedCanonicalNode.id}</strong></div><dl className="compact-metrics"><div><dt>Region</dt><dd>{selectedCanonicalNode.region??'Unassigned'}</dd></div><div><dt>Type</dt><dd>{selectedCanonicalNode.type??'Node'}</dd></div><div><dt>Availability</dt><dd>{selectedCanonicalNode.available===false||plannedOutageNodeIds.has(selectedCanonicalNode.id)?'Unavailable in plan':'Available'}</dd></div><div><dt>Plan state</dt><dd>{plannedChangedNodeIds.has(selectedCanonicalNode.id)?'Modified':'Unchanged'}</dd></div></dl><div className="inspector-actions"><button type="button" data-testid={`plan-node-outage-${selectedCanonicalNode.id}`} onClick={()=>handleNodeAvailability(selectedCanonicalNode.id,plannedOutageNodeIds.has(selectedCanonicalNode.id))}>{plannedOutageNodeIds.has(selectedCanonicalNode.id)?'Remove planned outage':'Add outage'}</button><label className="check-action"><input type="checkbox" data-testid={`lock-node-${selectedCanonicalNode.id}`} checked={lockedNodeIds.has(selectedCanonicalNode.id)} onChange={(event)=>runWorkspaceAction(()=>{workspaceService.setPlanRestriction('node',selectedCanonicalNode.id,event.target.checked,'human');})}/>Lock node</label><label className="check-action"><input type="checkbox" data-testid={`avoid-node-${selectedCanonicalNode.id}`} checked={(plan.restrictions.forbiddenRoutingNodeIds??[]).includes(selectedCanonicalNode.id)} onChange={(event)=>runWorkspaceAction(()=>{workspaceService.setRoutingRestriction('node',selectedCanonicalNode.id,event.target.checked,'human');})}/>Avoid in proposed routing</label></div></section>}
    {selectedCanonicalDemand&&<section className="inspector-section" data-testid={`demand-inspector-${selectedCanonicalDemand.id}`}><div className="inspector-title"><div><span>Demand</span><h3>{selectedCanonicalDemand.name??selectedCanonicalDemand.id}</h3></div><strong className="mono">{selectedCanonicalDemand.id}</strong></div><dl className="compact-metrics"><div><dt>Path</dt><dd>{selectedCanonicalDemand.source} → {selectedCanonicalDemand.target}</dd></div><div><dt>Bandwidth</dt><dd>{gbps(selectedCanonicalDemand.bandwidthGbps)}</dd></div><div><dt>Service class</dt><dd>{selectedCanonicalDemand.serviceClassId}</dd></div><div><dt>Default route</dt><dd>{!currentAnalysisVisible?'Not analyzed':selectedRoute?.reachable?`${selectedRoute.equalCostPathCountExact} equal-cost path${selectedRoute.equalCostPathCountExact===1?'':'s'} · ${allRouteLinks(selectedRoute).join(' / ')||'local'}`:'Unreachable'}</dd></div></dl>{selectedDesignVariant&&<div className="design-route-comparison" data-testid="selected-demand-design-routes"><span className="mini-label">Proposed · {selectedDesignVariant.label}</span>{selectedDesignRoutes.length?selectedDesignRoutes.map((row:any)=><div key={row.pathId} className="compact-copy"><strong>{Math.round(row.fraction*1000)/10}%</strong> {row.linkIds.join(' → ')||'local'}</div>):<p className="muted compact-copy">No proposed allocation for this demand.</p>}</div>}<button type="button" className="primary wide" data-testid="edit-demand-plan" onClick={()=>{setTrafficEditorOpen(true);setLeftPanelCollapsed(false);}}>Edit traffic plan</button></section>}
    {ephemeralPatch&&<section className="inspector-section counterexample-state"><span className="section-kicker">Counterexample replay</span><strong>{ephemeralPatch.name}</strong><button data-testid="return-to-plan" onClick={()=>{ephemeralRef.current=null;setEphemeralPatch(null);}}>Return to planned state</button></section>}
  </aside>;
  const analysisTabs:{id:AnalysisTab;label:string}[]=ANALYSIS_TABS.map((id)=>({id,label:id[0].toUpperCase()+id.slice(1)}));
  Object.assign(scope,{renderPlanResultSummary,renderInspector,analysisTabs});
}
