'use client';

import { useMemo, useState } from 'react';

type WorkbenchScope = any;
function pct(value:number){return `${Math.round(value*10)/10}%`;}
function gbps(value:number){return `${Math.round(value*100)/100} Gbps`;}
function ms(value:number){return `${Math.round(value*10)/10} ms`;}
function allRouteLinks(route:any):string[]{return route?Object.keys(route.linkFractions).filter((id)=>route.linkFractions[id]>0).sort():[];}
const VIOLATION_RENDER_BATCH_SIZE=200;
const ROUTE_RENDER_BATCH_SIZE=80;
const CONTINGENCY_RENDER_BATCH_SIZE=50;

export function WorkbenchM35dAnalysisView({scope}:{scope:WorkbenchScope}){
  const { activeView, project, authority, analysisStatusLabel, analysisTabs, analysisTab, setAnalysisTab, analysisAuthoritative, peak, analysis, plan, publishedPlanAnalysis, analysisFresh, analysisStatus, analysisMessage, resilienceStatus, resilienceMessage, progressLabel, pendingProposals, quickMitigation, comparison, snapshot, routeByDemand, setSelectedEvidence, visibleViolations, selectViolation, setViolationDisplay, n1Fresh, contingencies, canRunResilience, runPlanN1, ephemeralPatch, replayContingency, setActiveView, inspectCurrentBottleneck, bottleneck, compareDesignVariants, currentDesignState, selectedDesignVariant, canCompareDesignVariants, optimizerStatus, mitigationDisabledReason, n1DisabledReason } = scope;
  const [routeQuery,setRouteQuery]=useState('');
  const [routeFilter,setRouteFilter]=useState<'all'|'changed'|'unreachable'>('all');
  const [routeLimit,setRouteLimit]=useState(ROUTE_RENDER_BATCH_SIZE);
  const [contingencyLimit,setContingencyLimit]=useState(CONTINGENCY_RENDER_BATCH_SIZE);
  const designCompute=selectedDesignVariant?.candidatePathSet?.generationDiagnostics;
  const designCacheTotal=designCompute?(designCompute.cacheHits+designCompute.cacheMisses):0;
  const designCacheHitPct=designCacheTotal?Math.round((designCompute.cacheHits/designCacheTotal)*100):0;
  const routeRows=useMemo(()=>{
    const q=routeQuery.trim().toLowerCase();
    return snapshot.demands.filter((demand:any)=>{
      const route=routeByDemand.get(demand.id);
      const links=allRouteLinks(route);
      const matches=!q||[demand.id,demand.name,demand.serviceClassId,demand.source,demand.target,...links].filter(Boolean).join(' ').toLowerCase().includes(q);
      if(!matches)return false;
      if(routeFilter==='unreachable')return analysisAuthoritative && !route?.reachable;
      if(routeFilter==='changed')return links.some((id)=>scope.plannedChangedLinkIds?.has(id)||scope.proposalLinkIds?.has(id));
      return true;
    });
  },[snapshot.demands,routeByDemand,routeQuery,routeFilter,analysisAuthoritative,scope.plannedChangedLinkIds,scope.proposalLinkIds]);

  if(activeView !== 'analysis') return null;
  const mitigationUnavailable=!analysisAuthoritative||analysis.result.verdict!=='FAIL';
  const compareUnavailable=!canCompareDesignVariants||optimizerStatus==='running';
  const verify=selectedDesignVariant?.verification;
  const verificationRows=verify ? [
    ['Candidate path identity',verify.pathSetHashMatches],
    ['Demand conservation',verify.demandConservation],
    ['Allowed actions / locks',verify.validActions],
    ['Link loads / routing',verify.linkLoadsValid],
    ['Capacity / utilization',verify.utilizationValid],
    ['Budget',verify.budgetValid],
    ['Objective',verify.objectiveValid],
    ['Scenario coverage',verify.selectedScenariosValid],
  ] as [string,boolean][] : [];

  return <section className="destination-view analysis-view" data-testid="analysis-view">
    <header className="destination-heading"><div><span className="section-kicker">Analysis</span><h1>{project.name}</h1><p>Deterministic evidence for the live ChangePlan.</p></div><div className={`destination-verdict result-${authority.toLowerCase()}`}><strong>Current plan · {authority}</strong><span>{analysisStatusLabel}</span></div></header>
    <nav className="subtab-nav" aria-label="Analysis sections">{analysisTabs.map((tab:{id:any;label:string}) => <button key={tab.id} data-testid={`analysis-tab-${tab.id}`} className={analysisTab === tab.id ? 'active' : ''} onClick={() => setAnalysisTab(tab.id)}>{tab.label}</button>)}</nav>
    <div className="destination-scroll">
      {analysisTab === 'summary' && <div className="analysis-section" data-testid="analysis-summary"><div className="section-grid analysis-summary-grid">
        <section><h2>Current plan</h2><dl className="compact-metrics"><div><dt>Verdict</dt><dd>{authority}</dd></div><div><dt>Peak utilization</dt><dd>{analysisAuthoritative ? pct(peak) : 'Not analyzed'}</dd></div><div><dt>Unrouted demands</dt><dd>{analysisAuthoritative ? analysis.routing.unroutedDemandIds.length : '—'}</dd></div><div><dt>Target</dt><dd>{pct(plan.constraints.targetUtilizationPct)}</dd></div></dl>{publishedPlanAnalysis && <p>{analysisFresh ? publishedPlanAnalysis.reasons.join(' ') : 'Evidence is stale because the base network or ChangePlan changed.'}</p>}</section>
        <section><h2>Execution</h2>{analysisStatus==='running'?<div className="progress-card running"><strong>Analyzing current plan</strong><span className="indeterminate-progress" aria-hidden="true"/><p>{analysisMessage}</p></div>:<p>{analysisStatus === 'idle' ? 'No analysis is running.' : analysisMessage}</p>}{resilienceStatus !== 'idle' && <div className={`progress-card ${resilienceStatus}`} data-testid="analysis-resilience-status"><strong>N-1 {resilienceStatus}</strong>{resilienceStatus==='running'&&<span className="indeterminate-progress" aria-hidden="true"/>}<p>{resilienceMessage || progressLabel}</p></div>}</section>
        <section><h2>Mitigation</h2><p>{pendingProposals.length ? `${pendingProposals.length} proposed change${pendingProposals.length===1?' is':'s are'} awaiting human review.` : 'No mitigation proposal is pending.'}</p><div className="inline-actions"><button data-testid="propose-deterministic" disabled={mitigationUnavailable} title={mitigationUnavailable ? (mitigationDisabledReason ?? 'Analyze a failing plan first') : undefined} onClick={quickMitigation}>Find mitigation</button><button data-testid="compare-design-variants-analysis" disabled={compareUnavailable} title={compareUnavailable ? (optimizerStatus==='running'?'Alternative generation is running':'Analyze a failing plan with adaptive routing enabled first') : undefined} onClick={() => void compareDesignVariants()}>Compare alternatives</button></div>{comparison && <p>Candidate peak: {pct(comparison.after.routing.peakUtilizationPct)} from {pct(comparison.before.routing.peakUtilizationPct)}.</p>}{selectedDesignVariant && <div className="proposal-summary" data-testid="analysis-design-summary"><span className="state-chip proposed">Proposed</span><strong>{selectedDesignVariant.label}</strong><span>Cost {selectedDesignVariant.totalCost} · peak {pct(selectedDesignVariant.peakUtilizationPct)}</span><small>{selectedDesignVariant.verification.status==='verified'?'Verified proposal awaiting human review. Not applied to the base network.':'Verification needs attention.'}</small></div>}</section>
      </div></div>}

      {analysisTab === 'routes' && <div className="analysis-section" data-testid="analysis-routes"><div className="section-heading-row"><div><h2>Routes</h2><p>{routeRows.length.toLocaleString()} of {snapshot.demands.length.toLocaleString()} demands</p></div></div><div className="list-toolbar"><input aria-label="Search routes" placeholder="Search demand, service, node, or link" value={routeQuery} onChange={(e)=>{setRouteQuery(e.target.value);setRouteLimit(ROUTE_RENDER_BATCH_SIZE);}}/><select aria-label="Filter routes" value={routeFilter} onChange={(e)=>{setRouteFilter(e.target.value as any);setRouteLimit(ROUTE_RENDER_BATCH_SIZE);}}><option value="all">All routes</option><option value="changed">Planned / proposed paths</option><option value="unreachable">Unreachable only</option></select></div><div className="demand-list">{snapshot.demands.length === 0 ? <p className="empty">No demands in the effective snapshot.</p> : routeRows.slice(0,routeLimit).map((demand:any) => { const route = routeByDemand.get(demand.id); const links = allRouteLinks(route); const routeText=!analysisAuthoritative?'Not analyzed':route?.reachable?`${route.equalCostPathCountExact} equal-cost path${route.equalCostPathCountExact===1?'':'s'} · ${links.join(' / ') || 'local'}`:'Unreachable'; return <button className="demand-route standalone" key={demand.id} onClick={() => setSelectedEvidence({ type: 'route', id: `route:${demand.id}`, demandId: demand.id, linkIds: links })}><strong>{demand.name ?? demand.id}<span className="mono-inline">{demand.id}</span><span>{gbps(demand.bandwidthGbps)}</span></strong><small>{routeText} · {demand.serviceClassId}</small></button>; })}{routeLimit<routeRows.length&&<button className="secondary wide" onClick={()=>setRouteLimit(v=>Math.min(v+ROUTE_RENDER_BATCH_SIZE,routeRows.length))}>Show more · {routeLimit.toLocaleString()} / {routeRows.length.toLocaleString()} shown</button>}</div></div>}

      {analysisTab === 'violations' && <div className="analysis-section" data-testid="analysis-violations"><h2>Violations</h2><div className="violation-list">{!analysisAuthoritative ? <p className="empty">Analyze the current plan to publish authoritative violations.</p> : analysis.result.violations.length === 0 ? <p className="empty success-empty">No modeled routing or capacity violations.</p> : <>{visibleViolations.map((violation:any) => <button className="violation" key={violation.id} onClick={() => selectViolation(violation)}><strong>{violation.type.replaceAll('_', ' ')}</strong><p>{violation.message}</p></button>)}{visibleViolations.length < analysis.result.violations.length && <button type="button" className="secondary wide" data-testid="show-more-violations" onClick={() => setViolationDisplay({ resultId: analysis.result.id, count: Math.min(analysis.result.violations.length, visibleViolations.length + VIOLATION_RENDER_BATCH_SIZE) })}>Show more violations · {visibleViolations.length.toLocaleString()} / {analysis.result.violations.length.toLocaleString()} shown</button>}</>}</div></div>}

      {analysisTab === 'contingencies' && <div className="analysis-section" data-testid="analysis-contingencies"><div className="section-heading-row"><div><h2>Contingencies</h2><p>{n1Fresh && contingencies ? `${contingencies.completedScenarios}/${contingencies.totalEligibleScenarios} failures tested · ${contingencies.status.toUpperCase()}` : 'No current N-1 result.'}</p></div><button data-testid="run-resilience-analysis" disabled={!canRunResilience || resilienceStatus === 'running'} title={!canRunResilience ? (n1DisabledReason ?? 'N-1 is unavailable for the current state') : resilienceStatus==='running'?'N-1 analysis is already running':undefined} onClick={() => void runPlanN1()}>{resilienceStatus==='running'?'Running N-1…':'Run N-1'}</button></div>{contingencies && n1Fresh ? <><p className="list-count">Showing {Math.min(contingencyLimit,contingencies.cases.length).toLocaleString()} of {contingencies.cases.length.toLocaleString()} ranked contingencies.</p><div data-testid="contingency-list" className="contingency-list">{contingencies.cases.slice(0, contingencyLimit).map((item:any,index:number) => <button data-testid={`counterexample-${item.linkId}`} key={item.linkId} className={ephemeralPatch?.id === item.patch.id ? 'active' : ''} onClick={() => { replayContingency(item.linkId); setActiveView('network'); }}><span>#{index + 1} · {item.linkId}</span><strong>{item.verdict}</strong><small>score {item.score} · peak {pct(item.peakUtilizationPct)} · unsatisfied {gbps(item.unroutedDemandGbps)}</small></button>)}{contingencyLimit<contingencies.cases.length&&<button className="secondary wide" onClick={()=>setContingencyLimit(v=>Math.min(v+CONTINGENCY_RENDER_BATCH_SIZE,contingencies.cases.length))}>Show more</button>}</div></> : <p className="muted">Run bounded N-1 to generate replayable single-link cases.</p>}</div>}

      {analysisTab === 'bottlenecks' && <div className="analysis-section" data-testid="analysis-bottlenecks"><div className="section-heading-row"><div><h2>Bottlenecks</h2><p>Inspect deterministic min-cut evidence for the current failing flow.</p></div><button disabled={!analysisAuthoritative || analysis.result.verdict !== 'FAIL'} title={!analysisAuthoritative?'Analyze the current plan first':analysis.result.verdict!=='FAIL'?'Min-cut inspection is available for failing plans':undefined} onClick={inspectCurrentBottleneck}>Find min-cut bottleneck</button></div>{bottleneck ? <div className="evidence-block cut-block"><strong>{bottleneck.sourceId} → {bottleneck.targetId}: {gbps(bottleneck.cut.cutCapacityGbps)}</strong><p>Cut links: {bottleneck.cut.cutLinkIds.join(', ') || 'none'} · headroom {gbps(bottleneck.headroomGbps)}</p></div> : <p className="muted">No bottleneck inspection selected.</p>}</div>}

      {analysisTab === 'evidence' && <div className="analysis-section" data-testid="analysis-evidence"><div className="section-heading-row"><div><h2>Verification & evidence</h2><p>Decision evidence first; implementation provenance remains available below.</p></div><div className={`evidence-currentness ${analysisFresh ? 'current' : 'stale'}`}><span>Current-plan evidence</span><strong>{analysisFresh ? 'Current' : publishedPlanAnalysis ? 'Stale' : 'Not published'}</strong></div></div>{selectedDesignVariant ? <div className="verification-layout"><section className="verification-card" data-testid="adaptive-design-evidence"><div className="verification-hero"><span className="state-chip proposed">Proposed design</span><strong className={verify?.status==='verified'?'verified-text':'warning-text'}>{verify?.status==='verified'?'VERIFIED':'NEEDS REVIEW'}</strong><span>{selectedDesignVariant.label} · peak {pct(selectedDesignVariant.peakUtilizationPct)} · cost {selectedDesignVariant.totalCost}</span><small>Verified does not mean applied. This proposal remains pending human review.</small></div><dl className="verification-checklist">{verificationRows.map(([label,ok])=><div key={label}><dt>{label}</dt><dd className={ok?'pass':'fail'}>{ok?'Passed':'Failed'}</dd></div>)}</dl>{verify?.violations?.length?<div className="verification-violations"><strong>Verification disagreements</strong>{verify.violations.map((v:string)=><p key={v}>{v}</p>)}</div>:<p className="verification-note">Independent verification passed.</p>}</section><section className="verification-context"><h3>Scenario coverage</h3><p>{selectedDesignVariant.scenarioPassCount} / {selectedDesignVariant.scenarioCount} modeled scenarios pass.</p><h3>Design actions</h3><p>{selectedDesignVariant.evidence.routingAllocationSummary.length ? `${selectedDesignVariant.evidence.routingAllocationSummary.length} adaptive routing allocation${selectedDesignVariant.evidence.routingAllocationSummary.length===1?'':'s'} changed` : 'No adaptive routing changes'} · {selectedDesignVariant.selectedUpgrades.length ? `${selectedDesignVariant.selectedUpgrades.length} capacity upgrade${selectedDesignVariant.selectedUpgrades.length===1?'':'s'}` : 'No capacity upgrades'} · {selectedDesignVariant.selectedNewLinks.length ? `${selectedDesignVariant.selectedNewLinks.length} declared new link${selectedDesignVariant.selectedNewLinks.length===1?'':'s'}` : 'No new links'}.</p>{currentDesignState?.variants.length ? <p><strong>{currentDesignState.variants.length} verified alternative{currentDesignState.variants.length===1?'':'s'} available.</strong> Compare them in Plans.</p> : null}</section></div> : <p className="muted">No adaptive design is selected. Deterministic current-plan evidence remains available below.</p>}
        <details className="technical-provenance"><summary>Technical provenance</summary>{selectedDesignVariant && <div className="evidence-block"><p>Path set <span className="mono-inline">{selectedDesignVariant.candidatePathSet.hash}</span> · solver {selectedDesignVariant.evidence.solver} {selectedDesignVariant.evidence.solverVersion ?? ''} · status {selectedDesignVariant.evidence.solverStatus} · objective {selectedDesignVariant.evidence.objective}.</p><small>Scenarios: {selectedDesignVariant.evidence.selectedScenarioIds.map((id:any,index:number) => `${id}@${selectedDesignVariant.evidence.selectedScenarioHashes[index]}`).join(', ') || 'baseline'}</small>{designCompute && <small data-testid="adaptive-design-compute">Compiled graph · {designCompute.uniqueSourceTargetPairs} unique route pair{designCompute.uniqueSourceTargetPairs===1?'':'s'} · cache {designCacheHitPct}% hit · path generation {ms(designCompute.totalMs)} · graph compile {ms(designCompute.graphCompileMs)} · retained cache ≈ {Math.round(designCompute.approximateRetainedCacheBytes/1024)} KiB</small>}</div>}{analysisAuthoritative && analysis.result.witnesses.length ? <div className="evidence-list">{analysis.result.witnesses.slice(0, 100).map((witness:any) => <button key={witness.id} onClick={() => setSelectedEvidence(witness)}><strong>{witness.type}</strong><span>{witness.id}</span></button>)}</div> : <p className="muted">No published deterministic analysis witnesses for the current plan.</p>}</details>
      </div>}
    </div>
  </section>;
}
