'use client';

import { N1_ENGINE_HARD_CAP } from '../lib/analysis-execution';

function pct(value:number){return `${Math.round(value*10)/10}%`;}

export function WorkbenchM35dAdvancedView({scope}:{scope:any}){
  const { advancedOpen, setAdvancedOpen, currentProjectHash, currentPlanHash, analysisFresh, publishedPlanAnalysis, executionProfile, compute, lastAnalysisRuntimeMs, lastAnalysisExecution, contingencies, n1Fresh, eligibleN1, routingLpEstimate, optimizerStatus, optimizerMessage, capacityMilpEstimate, optimizerResult, candidateVerification, verificationFresh, runRoutingOptimizer, routingOptimization, webmcpStatus, registeredTools, lastToolAnalysis, activity } = scope;
  return <aside className={`advanced-drawer ${advancedOpen ? 'open' : ''}`} data-testid="advanced-drawer" aria-hidden={!advancedOpen}>
    <header><div><span className="section-kicker">Developer details</span><h2>Diagnostics and provenance</h2></div><button aria-label="Close advanced details" onClick={() => setAdvancedOpen(false)}>×</button></header>
    <div className="advanced-scroll">
      <section><h3>Provenance</h3><dl className="advanced-list"><div><dt>Base model hash</dt><dd data-testid="base-model-hash" className="mono">{currentProjectHash}</dd></div><div><dt>Change Plan hash</dt><dd data-testid="plan-hash" className="mono">{currentPlanHash}</dd></div><div><dt>Evidence</dt><dd>{analysisFresh ? 'Current' : publishedPlanAnalysis ? 'Stale' : 'Not published'}</dd></div></dl></section>
      <section data-testid="compute-profile"><h3>Compute profile</h3><p>{executionProfile.mode === 'worker' ? 'Worker preferred' : 'Main-thread fast path'}</p><dl className="advanced-list"><div><dt>Execution</dt><dd>{executionProfile.mode}</dd></div><div><dt>Estimated work</dt><dd>{executionProfile.estimatedWorkUnits.toLocaleString()}</dd></div><div><dt>Workers</dt><dd>{compute.workerSupported ? `${compute.recommendedWorkerCount} recommended` : 'unsupported'}</dd></div><div><dt>SharedArrayBuffer</dt><dd>{compute.sharedArrayBufferSupported ? 'available' : 'unavailable'}</dd></div><div><dt>Last analysis</dt><dd>{lastAnalysisRuntimeMs === null ? 'not run' : `Last execution: ${lastAnalysisExecution} · ${lastAnalysisRuntimeMs} ms live`}</dd></div><div><dt>N-1 coverage</dt><dd>{contingencies && n1Fresh ? `${contingencies.completedScenarios}/${contingencies.totalEligibleScenarios} ${contingencies.status.toUpperCase()}` : `${eligibleN1} eligible link failures`}</dd></div><div><dt>Routing LP</dt><dd>{routingLpEstimate.recommended ? 'RECOMMENDED' : 'NOT RECOMMENDED'}</dd></div></dl></section>
      <section><h3>Optimizer diagnostics</h3><div data-testid="optimizer-status" className={`compute-card ${optimizerStatus === 'error' ? 'error' : optimizerStatus === 'running' ? 'running' : 'complete'}`}><strong>{optimizerStatus} · HiGHS WASM</strong><p>{optimizerMessage}</p></div><p>Capacity MILP: {capacityMilpEstimate.reason}</p>{optimizerResult && <div data-testid="capacity-optimizer-result"><strong>{optimizerResult.diagnostics.status} · {optimizerResult.diagnostics.proof}</strong><p>{optimizerResult.selectedUpgrades.length} upgrade(s) · objective {optimizerResult.diagnostics.objectiveValue ?? 'n/a'}</p></div>}{candidateVerification && <div data-testid="candidate-verification"><strong>{verificationFresh ? candidateVerification.status.toUpperCase() : 'STALE'}</strong><p>{verificationFresh ? candidateVerification.violations.join(' ') || `Verified cost ${candidateVerification.calculatedCost}` : 'Plan/proposal revision changed after verification.'}</p></div>}<button data-testid="routing-lp-action" onClick={() => void runRoutingOptimizer()}>Solve diagnostic routing LP</button><p data-testid="routing-lp-guidance">{routingLpEstimate.reason}</p>{routingOptimization && <div data-testid="routing-lp-result"><strong>{routingOptimization.diagnostics.status}</strong><p>Minimum max utilization {routingOptimization.maxUtilizationPct === null ? 'n/a' : pct(routingOptimization.maxUtilizationPct)}</p></div>}</section>
      <section data-testid="advanced-inspector"><h3>WebMCP diagnostics</h3><p>Status: {webmcpStatus}. {registeredTools.length} registered capabilities.</p>{webmcpStatus === 'unsupported' && <p>WebMCP is not available in this browser. Core planning remains fully usable.</p>}<div className="tool-badges">{registeredTools.map((name:string) => <span key={name}>{name}</span>)}</div>{lastToolAnalysis && <p>Latest tool-published analysis: {lastToolAnalysis}</p>}<div className="activity-list">{activity.length === 0 ? <p className="muted">No tool activity recorded.</p> : activity.map((event:any) => <div key={event.id} className="activity-row"><time>{event.startedAt.slice(11, 19)}</time><span>{event.tool}</span><strong>{event.status}</strong><small>{event.summary} · {event.durationMs} ms</small></div>)}</div></section>
      <section><h3>Scale guards</h3><dl className="advanced-list"><div><dt>N-1 eligible</dt><dd>{eligibleN1} · engine cap {N1_ENGINE_HARD_CAP}</dd></div><div><dt>Routing LP</dt><dd>{routingLpEstimate.flowVariables.toLocaleString()} flow variables</dd></div><div><dt>Capacity MILP</dt><dd>{capacityMilpEstimate.decisionScenarioProduct.toLocaleString()} decision×scenario</dd></div></dl></section>
    </div>
  </aside>;
}
