'use client';
type WorkbenchScope = any;
function pct(value:number){return `${Math.round(value*10)/10}%`;}
function gbps(value:number){return `${Math.round(value*100)/100} Gbps`;}
function ms(value:number){return `${Math.round(value*10)/10} ms`;}
function allRouteLinks(route:any):string[]{return route?Object.keys(route.linkFractions).filter((id)=>route.linkFractions[id]>0).sort():[];}
const VIOLATION_RENDER_BATCH_SIZE=200;
export function WorkbenchM35dAnalysisView({scope}:{scope:WorkbenchScope}){
  const { activeView, project, authority, analysisStatusLabel, analysisTabs, analysisTab, setAnalysisTab, analysisAuthoritative, peak, analysis, plan, publishedPlanAnalysis, analysisFresh, analysisStatus, analysisMessage, resilienceStatus, resilienceMessage, progressLabel, pendingProposals, quickMitigation, comparison, snapshot, routeByDemand, setSelectedEvidence, visibleViolations, selectViolation, setViolationDisplay, n1Fresh, contingencies, canRunResilience, runPlanN1, ephemeralPatch, replayContingency, setActiveView, inspectCurrentBottleneck, bottleneck, compareDesignVariants, currentDesignState, selectedDesignVariant, canCompareDesignVariants, optimizerStatus } = scope;
  const designCompute=selectedDesignVariant?.candidatePathSet?.generationDiagnostics;
  const designCacheTotal=designCompute?(designCompute.cacheHits+designCompute.cacheMisses):0;
  const designCacheHitPct=designCacheTotal?Math.round((designCompute.cacheHits/designCacheTotal)*100):0;
  return (activeView === 'analysis' && <section className="destination-view analysis-view" data-testid="analysis-view">
        <header className="destination-heading"><div><span className="section-kicker">Analysis</span><h1>{project.name}</h1></div><div className={`destination-verdict result-${authority.toLowerCase()}`}><strong>{authority}</strong><span>{analysisStatusLabel}</span></div></header>
        <nav className="subtab-nav" aria-label="Analysis sections">{analysisTabs.map((tab:{id:any;label:string}) => <button key={tab.id} data-testid={`analysis-tab-${tab.id}`} className={analysisTab === tab.id ? 'active' : ''} onClick={() => setAnalysisTab(tab.id)}>{tab.label}</button>)}</nav>
        <div className="destination-scroll">
          {analysisTab === 'summary' && <div className="analysis-section" data-testid="analysis-summary"><div className="section-grid"><section><h2>Current result</h2><dl className="compact-metrics"><div><dt>Verdict</dt><dd>{authority}</dd></div><div><dt>Peak utilization</dt><dd>{analysisAuthoritative ? pct(peak) : 'Not analyzed'}</dd></div><div><dt>Unrouted demands</dt><dd>{analysisAuthoritative ? analysis.routing.unroutedDemandIds.length : '—'}</dd></div><div><dt>Target</dt><dd>{pct(plan.constraints.targetUtilizationPct)}</dd></div></dl>{publishedPlanAnalysis && <p>{analysisFresh ? publishedPlanAnalysis.reasons.join(' ') : 'Evidence is stale because the base network or Change Plan changed.'}</p>}</section><section><h2>Execution</h2><p>{analysisStatus === 'idle' ? 'No explicit analysis run is active.' : analysisMessage}</p>{resilienceStatus !== 'idle' && <div data-testid="analysis-resilience-status"><strong>N-1 {resilienceStatus}</strong><p>{resilienceMessage || progressLabel}</p></div>}</section><section><h2>Mitigation</h2><p>{pendingProposals.length ? `${pendingProposals.length} proposal changes are waiting for review in the Change Plan.` : 'No mitigation proposal is pending.'}</p><div className="inline-actions"><button data-testid="propose-deterministic" disabled={!analysisAuthoritative || analysis.result.verdict !== 'FAIL'} onClick={quickMitigation}>Find mitigation</button><button data-testid="compare-design-variants-analysis" disabled={!canCompareDesignVariants || optimizerStatus === 'running'} onClick={() => void compareDesignVariants()}>Compare alternatives</button></div>{comparison && <p>Candidate peak: {pct(comparison.after.routing.peakUtilizationPct)} from {pct(comparison.before.routing.peakUtilizationPct)}.</p>}{selectedDesignVariant && <div className="evidence-block" data-testid="analysis-design-summary"><strong>{selectedDesignVariant.label} · cost {selectedDesignVariant.totalCost} · peak {pct(selectedDesignVariant.peakUtilizationPct)}</strong><p>{selectedDesignVariant.selectedUpgrades.map((item:any) => `${item.linkId}→${item.toCapacityGbps} Gbps`).join(', ') || 'No capacity upgrade'}{selectedDesignVariant.selectedNewLinks.length ? ` · new ${selectedDesignVariant.selectedNewLinks.map((item:any) => item.id).join(', ')}` : ''} · {selectedDesignVariant.evidence.routingAllocationSummary.length} routing allocation change(s).</p></div>}</section></div></div>}
          {analysisTab === 'routes' && <div className="analysis-section" data-testid="analysis-routes"><h2>Routes</h2><div className="demand-list">{snapshot.demands.length === 0 ? <p className="empty">No demands in the effective snapshot.</p> : snapshot.demands.map((demand:any) => { const route = routeByDemand.get(demand.id); const links = allRouteLinks(route); return <button className="demand-route standalone" key={demand.id} onClick={() => setSelectedEvidence({ type: 'route', id: `route:${demand.id}`, demandId: demand.id, linkIds: links })}><strong>{demand.id} · {demand.name ?? demand.id} · {gbps(demand.bandwidthGbps)}</strong><small>{route?.reachable ? `${route.equalCostPathCountExact} equal-cost path(s) · ${links.join(' / ') || 'local'}` : 'unreachable'} · {demand.serviceClassId}</small></button>; })}</div></div>}
          {analysisTab === 'violations' && <div className="analysis-section" data-testid="analysis-violations"><h2>Violations</h2><div className="violation-list">{!analysisAuthoritative ? <p className="empty">Analyze the current plan to publish authoritative violations.</p> : analysis.result.violations.length === 0 ? <p className="empty">No modeled routing/capacity violations.</p> : <>{visibleViolations.map((violation:any) => <button className="violation" key={violation.id} onClick={() => selectViolation(violation)}><strong>{violation.type.replaceAll('_', ' ')}</strong><p>{violation.message}</p></button>)}{visibleViolations.length < analysis.result.violations.length && <button type="button" className="secondary wide" data-testid="show-more-violations" onClick={() => setViolationDisplay({ resultId: analysis.result.id, count: Math.min(analysis.result.violations.length, visibleViolations.length + VIOLATION_RENDER_BATCH_SIZE) })}>Show more violations · {visibleViolations.length.toLocaleString()} / {analysis.result.violations.length.toLocaleString()} shown</button>}</>}</div></div>}
          {analysisTab === 'contingencies' && <div className="analysis-section" data-testid="analysis-contingencies"><div className="section-heading-row"><div><h2>Contingencies</h2><p>{n1Fresh && contingencies ? `${contingencies.completedScenarios}/${contingencies.totalEligibleScenarios} failures tested · ${contingencies.status.toUpperCase()}` : 'No current N-1 result.'}</p></div><button data-testid="run-resilience-analysis" disabled={!canRunResilience || resilienceStatus === 'running'} onClick={() => void runPlanN1()}>Run N-1</button></div>{contingencies && n1Fresh ? <div data-testid="contingency-list" className="contingency-list">{contingencies.cases.slice(0, 50).map((item:any,index:number) => <button data-testid={`counterexample-${item.linkId}`} key={item.linkId} className={ephemeralPatch?.id === item.patch.id ? 'active' : ''} onClick={() => { replayContingency(item.linkId); setActiveView('network'); }}><span>#{index + 1} · {item.linkId}</span><strong>{item.verdict}</strong><small>score {item.score} · peak {pct(item.peakUtilizationPct)} · unsatisfied {gbps(item.unroutedDemandGbps)}</small></button>)}</div> : <p className="muted">Run exact bounded N-1 to generate replayable single-link cases.</p>}</div>}
          {analysisTab === 'bottlenecks' && <div className="analysis-section" data-testid="analysis-bottlenecks"><div className="section-heading-row"><div><h2>Bottlenecks</h2><p>Inspect deterministic min-cut evidence for the current failing flow.</p></div><button disabled={!analysisAuthoritative || analysis.result.verdict !== 'FAIL'} onClick={inspectCurrentBottleneck}>Find min-cut bottleneck</button></div>{bottleneck ? <div className="evidence-block cut-block"><strong>{bottleneck.sourceId} → {bottleneck.targetId}: {gbps(bottleneck.cut.cutCapacityGbps)}</strong><p>Cut links: {bottleneck.cut.cutLinkIds.join(', ') || 'none'} · headroom {gbps(bottleneck.headroomGbps)}</p></div> : <p className="muted">No bottleneck inspection selected.</p>}</div>}
          {analysisTab === 'evidence' && <div className="analysis-section" data-testid="analysis-evidence"><h2>Evidence</h2><div className={`evidence-currentness ${analysisFresh ? 'current' : 'stale'}`}><span>Evidence</span><strong>{analysisFresh ? '✓ Current' : publishedPlanAnalysis ? 'STALE' : 'Not published'}</strong></div>{selectedDesignVariant && <div className="evidence-block" data-testid="adaptive-design-evidence"><strong>Adaptive design · {selectedDesignVariant.verification.status.toUpperCase()}</strong><p>Path set {selectedDesignVariant.candidatePathSet.hash} · solver {selectedDesignVariant.evidence.solver} {selectedDesignVariant.evidence.solverVersion ?? ''} · status {selectedDesignVariant.evidence.solverStatus} · objective {selectedDesignVariant.evidence.objective} · peak {pct(selectedDesignVariant.peakUtilizationPct)}.</p><small>Scenarios: {selectedDesignVariant.evidence.selectedScenarioIds.map((id:any,index:number) => `${id}@${selectedDesignVariant.evidence.selectedScenarioHashes[index]}`).join(', ') || 'baseline'} · reconstructed primal verification: {selectedDesignVariant.verification.violations.length ? selectedDesignVariant.verification.violations.join('; ') : 'passed'}</small>{designCompute && <small data-testid="adaptive-design-compute">Adaptive compute · TypeScript compiled graph · {designCompute.uniqueSourceTargetPairs} unique route pair(s) · cache {designCacheHitPct}% hit · path generation {ms(designCompute.totalMs)} · graph compile {ms(designCompute.graphCompileMs)} · retained cache ≈ {Math.round(designCompute.approximateRetainedCacheBytes/1024)} KiB</small>}</div>}{currentDesignState?.variants.length ? <p className="muted compact-copy">Current design frontier: {currentDesignState.variants.length} nondominated verified variant(s).</p> : null}{analysisAuthoritative && analysis.result.witnesses.length ? <div className="evidence-list">{analysis.result.witnesses.slice(0, 100).map((witness:any) => <button key={witness.id} onClick={() => setSelectedEvidence(witness)}><strong>{witness.type}</strong><span>{witness.id}</span></button>)}</div> : <p className="muted">No published deterministic analysis witnesses for the current plan.</p>}</div>}
        </div>
      </section>);
}
